### ISSUE TITLE
Improved default security for Pelias service dependencies (Elastic Search, etc)

### ISSUE THREAD

**Issue by Jezternz** [pelias/docker#254]
### Use-cases
Currently if you deploy Pelias Docker containers to a public facing space, there is a good chance you will stumble into a world of pain. In my specific case I setup Pelias, a week later had a ransomware attack, removing all indexes (and presumably bitlockering them). Although this does feel like an administrative problem, there are simple changes to the docker-compose files that could resolve this.

### Proposal
I believe it would make sense to have a reasonable (docker) network access policy by default that only exposes the pelias api itself. This would require changes to the docker-compose file, what I had envisioned is basically described [here](https://stackoverflow.com/a/51964169/685404).

I would expect the pelias api to be publicly exposed (as it is effectively read-only) and all the other (vulnerable) services (such as elasticsearch) to be exposed only on a private network. I realize this will limit access to the non-pelias API's, and may add a barrier for debugging, however this feels like a reasonable price to pay given how vulnerable the docker containers are in their default state. 

Maybe a reasonable solution would be to use an optional env parameter named something like "**SERVICE_DEPENDENCIES_PRIVATE**=" with a default of true (or false if that's preferable), this could sit beside DATA_DIR= in the .env file. Additionally this would require a change to the dockercompose.yml to be something like:
```
networks:
  net-pelias-deps:
    driver: bridge
    internal: '${SERVICE_DEPENDENCIES_PUBLIC}'
  net-pelias-api:
    driver: bridge
api:
    ...other config
    networks:
      - net-pelias-deps
      - net-pelias-api
...other services
    ...other config
    networks:
      - net-pelias-deps
```

### References
[Other example of someone who suffered a similar fate](https://github.com/pelias/docker/issues/209)
