### ISSUE TITLE
Interpolation error

### ISSUE THREAD

**Issue by MiesSuomesta** [pelias/docker#348]
Hi All!

**Describe the bug**
  I'm trying to get Pelias working, but now it fails to locate SQL 
 database, and error does not include what & where.

**Steps to Reproduce**
docker compose up in pelias project directory.

**Expected behavior**
 No errors

**Environment:**
 - OS: Linux
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        24.0.1
Codename:       Wynsdey

 - Docker version:
   Docker version 26.1.3, build b72abbb6f0 

**Pastebin/Screenshots**
```
pelias_interpolation  | TypeError: Cannot open database because the directory does not exist
pelias_interpolation  |     at new Database (/code/pelias/interpolation/node_modules/better-sqlite3/lib/database.js:59:9)
pelias_interpolation  |     at setup (/code/pelias/interpolation/api/search.js:12:14)
pelias_interpolation  |     at Object.<anonymous> (/code/pelias/interpolation/cmd/server.js:32:11)
pelias_interpolation  |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
pelias_interpolation  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
pelias_interpolation  |     at Module.load (node:internal/modules/cjs/loader:1076:32)
pelias_interpolation  |     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
pelias_interpolation  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
pelias_interpolation  |     at node:internal/main/run_main_module:22:47
pelias_interpolation  | /code/pelias/interpolation/node_modules/better-sqlite3/lib/database.js:59
pelias_interpolation  |                 throw new TypeError('Cannot open database because the directory does not exist');
```

**Additional context**
Pelias config as follows:
```
{
  "esclient": {
    "apiVersion": "7.x",
    "keepAlive": true,
    "requestTimeout": "120000",
    "hosts": [{
      "env": "development",
      "protocol": "http",
      "host": "localhost",
      "port": 9200
    }],
    "log": [{
      "type": "stdio",
      "json": false,
      "level": [ "error", "warning", "info", "debug" ]
    }]
  },
  "elasticsearch": {
    "settings": {
      "index": {
        "number_of_replicas": "0",
        "number_of_shards": "5",
        "refresh_interval": "1m"
      }
    }
  },
  "interpolation": {
    "client": {
      "adapter": "null"
    }
  },
  "dbclient": {
    "statFrequency": 10000,
    "batchSize": 500
  },
  "api": {
    "services": {
      "placeholder":   { "url": "http://placeholder:4100" },
      "pip":           { "url": "http://pip:4200" },
      "interpolation": { "url": "http://interpolation:4300" },
      "libpostal":     { "url": "http://libpostal:4400" }
    },
    "accessLog": "common",
    "host": "http://pelias.mapzen.com/",
    "indexName": "pelias",
    "version": "1.0",
    "targets": {
      "auto_discover": true,
      "canonical_sources": ["whosonfirst", "openstreetmap", "openaddresses", "geonames"],
      "layers_by_source": {
        "openstreetmap": [ "address", "venue", "street" ],
        "openaddresses": [ "address" ],
        "geonames": [
          "country", "macroregion", "region", "county", "localadmin", "locality", "borough",
          "neighbourhood", "venue"
        ],
        "whosonfirst": [
          "continent", "empire", "country", "dependency", "macroregion", "region", "locality",
          "localadmin", "macrocounty", "county", "macrohood", "borough", "neighbourhood",
          "microhood", "disputed", "venue", "postalcode", "ocean", "marinearea"
        ]
      },
      "source_aliases": {
        "osm": [ "openstreetmap" ],
        "oa":  [ "openaddresses" ],
        "gn":  [ "geonames" ],
        "wof": [ "whosonfirst" ]
      },
      "layer_aliases": {
        "coarse": [
          "continent", "empire", "country", "dependency", "macroregion", "region", "locality",
          "localadmin", "macrocounty", "county", "macrohood", "borough", "neighbourhood",
          "microhood", "disputed", "postalcode", "ocean", "marinearea"
        ]
      }
    }
  },
  "schema": {
    "indexName": "pelias"
  },
  "logger": {
    "level": "info",
    "timestamp": true,
    "colorize": true
  },
  "acceptance-tests": {
    "endpoints": {
      "local": "http://localhost:3100/v1/"
    }
  },
  "imports": {
    "adminLookup": {
      "enabled": true,
      "maxConcurrentRequests": 100,
      "usePostalCities": true
    },
    "blacklist": {
      "files": []
    },
    "csv": {
    },
    "geonames": {
      "datapath": "./theData/geonames",
      "countryCode": "FI"
    },
    "openstreetmap": {
      "datapath": "./theData/openstreetmap",
      "leveldbpath": "./theData",
      "import": [{
        "filename": "finland-latest.osm.pbf"
      }]
    },
    "openaddresses": {
      "datapath": "./theData/openaddresses",
      "token": "oa.bbbcf5787bb4251445883cc417f811ba02b9fd64809fd56c5a972171fbcfb2f6",
      "files": [ "fi/countrywide-fi.csv", "fi/countrywide-sv.csv" ]
    },
    "polyline": {
      "datapath": "./theData/polyline",
      "files": []
    },
    "whosonfirst": {
      "datapath": "./theData/whosonfirst",
      "importPostalcodes": true
    }
  }
}
```

Elasticsearch conf:
```
network.host: 0.0.0.0
bootstrap.memory_lock: true
indices.breaker.fielddata.limit: 85%
indices.fielddata.cache.size: 75%

# My additions:
xpack.ml.enabled: false
```
docker-compose.yml
```
version: '3'
networks:
  default:
    driver: bridge
    name: pelias-net
services:
  libpostal:
    image: pelias/libpostal-service
    container_name: pelias_libpostal
    restart: always
    ports: [ "4400:4400" ]
  schema:
    image: pelias/schema:master
    container_name: pelias_schema
    volumes:
      - "./pelias.json:/code/pelias.json"
  api:
    image: pelias/api:master
    container_name: pelias_api
    restart: always
    environment: [ "PORT=4000" ]
    ports: [ "4000:4000" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
  placeholder:
    image: pelias/placeholder:master
    container_name: pelias_placeholder
    restart: always
    environment:
      - PORT=4100
      - PLACEHOLDER_DATA=/data/placeholder
    ports: [ "4100:4100" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
      - "./blacklist/:/data/blacklist"
  whosonfirst:
    image: pelias/whosonfirst:master
    container_name: pelias_whosonfirst
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  openstreetmap:
    image: pelias/openstreetmap:master
    container_name: pelias_openstreetmap
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  openaddresses:
    image: pelias/openaddresses:master
    container_name: pelias_openaddresses
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  csv-importer:
    image: pelias/csv-importer:master
    container_name: pelias_csv_importer
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
      - "./blacklist/:/data/blacklist"
  polylines:
    image: pelias/polylines:master
    container_name: pelias_polylines
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  interpolation:
    image: pelias/interpolation:master
    container_name: pelias_interpolation
    restart: always
    environment: [ "PORT=4300" ]
    ports: [ "4300:4300" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  pip:
    image: pelias/pip-service:master
    container_name: pelias_pip-service
    restart: always
    environment: [ "PORT=4200" ]
    ports: [ "4200:4200" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  elasticsearch:
    image: pelias/elasticsearch:7.16.1
    container_name: pelias_elasticsearch
    restart: always
    ports: [ "9200:9200", "9300:9300" ]
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - ES_HEAP_SIZE=20g
    mem_limit: 20g
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - "${DATA_DIR}:/usr/share/elasticsearch/data"
      - ./pelias.json:/code/pelias.json
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add: [ "IPC_LOCK" ]
    security_opt:
      - seccomp=unconfined
```

Thanks in advance!
